# Generated by Django 5.2.8 on 2026-02-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('uz', 'Uzbek'), ('ru', 'Russian')], default='uz', help_text='Preferred language', max_length=10, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter your phone number', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address for OTP', max_length=254, verbose_name='Email')),
                ('code', models.CharField(help_text='6-digit OTP code', max_length=6, verbose_name='Code')),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('password_reset', 'Password Reset')], help_text='Purpose of the OTP', max_length=20, verbose_name='Purpose')),
                ('is_used', models.BooleanField(default=False, help_text='Whether the OTP has been used', verbose_name='Is Used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(help_text='Expiration time of the OTP', verbose_name='Expires At')),
            ],
            options={
                'verbose_name': 'OTP Code',
                'verbose_name_plural': 'OTP Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'code', 'purpose'], name='users_otpco_email_e325dc_idx')],
            },
        ),
    ]
