# Generated by Django 5.2.8 on 2026-02-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesaver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='short_summary',
        ),
        migrations.AddField(
            model_name='task',
            name='document_language',
            field=models.CharField(blank=True, choices=[('uz', "O'zbek"), ('ru', 'Rus'), ('en', 'Ingliz')], max_length=10, null=True, verbose_name='Hujjat tili'),
        ),
        migrations.AddField(
            model_name='task',
            name='document_title',
            field=models.CharField(default='Untitled Document', max_length=500, verbose_name='Hujjat sarlavhasi / Qisqacha mazmuni'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='incoming_ref_date',
            field=models.DateField(blank=True, null=True, verbose_name='Kirish sanasi'),
        ),
        migrations.AddField(
            model_name='task',
            name='incoming_ref_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kirish raqami'),
        ),
        migrations.AddField(
            model_name='task',
            name='received_channel',
            field=models.CharField(choices=[('courier', 'Kuryer'), ('mail', 'Pochta'), ('email', 'Elektron pochta'), ('portal', 'Portal'), ('hand_delivery', "Qo'lda"), ('other', 'Boshqa')], default='courier', max_length=255, verbose_name='Kelib tushish kanali'),
        ),
        migrations.AddField(
            model_name='task',
            name='received_date',
            field=models.DateField(default='2026-01-01', verbose_name='Kelib tushgan sana'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='sender_org_name',
            field=models.CharField(default='Unknown Org', max_length=500, verbose_name='Yuboruvchi tashkilot nomi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='sender_person_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yuboruvchi shaxs ismi'),
        ),
        migrations.AddField(
            model_name='task',
            name='sender_person_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yuboruvchi lavozimi'),
        ),
        migrations.AddField(
            model_name='task',
            name='sensitivity_level',
            field=models.CharField(choices=[('normal', 'Oddiy'), ('for_official_use', 'Xizmat doirasida foydalanish uchun'), ('confidential', 'Maxfiy')], default='normal', max_length=255, verbose_name='Maxfiylik darajasi'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Jarayonda'), ('completed', 'Bajarildi')], default='pending', max_length=255, verbose_name='Status'),
        ),
    ]
